// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoKgFwdfrfToX3L8-vhC4JQN-uuihZe0I',
    appId: '1:685600365624:web:a32391368268e606829acd',
    messagingSenderId: '685600365624',
    projectId: 'fluttercompareapp',
    authDomain: 'fluttercompareapp.firebaseapp.com',
    storageBucket: 'fluttercompareapp.appspot.com',
    measurementId: 'G-80S413LDF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrye3B5zRLTC324zKRSnpHi7raSTCl2HE',
    appId: '1:685600365624:android:ce977fac41772a1e829acd',
    messagingSenderId: '685600365624',
    projectId: 'fluttercompareapp',
    storageBucket: 'fluttercompareapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAld_nEXeMw9lYK3HWcL4CJs55MOF13KhE',
    appId: '1:685600365624:ios:95ed72e2be4e688c829acd',
    messagingSenderId: '685600365624',
    projectId: 'fluttercompareapp',
    storageBucket: 'fluttercompareapp.appspot.com',
    androidClientId: '685600365624-atollgbpl25br15pcouc9vv00222v89c.apps.googleusercontent.com',
    iosClientId: '685600365624-t6kd5321s4mijtasg332cva5rb0tnk0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCompareApp.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAld_nEXeMw9lYK3HWcL4CJs55MOF13KhE',
    appId: '1:685600365624:ios:65889362ccecdcfa829acd',
    messagingSenderId: '685600365624',
    projectId: 'fluttercompareapp',
    storageBucket: 'fluttercompareapp.appspot.com',
    androidClientId: '685600365624-atollgbpl25br15pcouc9vv00222v89c.apps.googleusercontent.com',
    iosClientId: '685600365624-eup6gg58brt002qsglpcptsi6n2rsvuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttercompareapp',
  );
}
