// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrye3B5zRLTC324zKRSnpHi7raSTCl2HE',
    appId: '1:685600365624:android:6b6f6b604c797840829acd',
    messagingSenderId: '685600365624',
    projectId: 'fluttercompareapp',
    storageBucket: 'fluttercompareapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAld_nEXeMw9lYK3HWcL4CJs55MOF13KhE',
    appId: '1:685600365624:ios:d42b34d1c5221990829acd',
    messagingSenderId: '685600365624',
    projectId: 'fluttercompareapp',
    storageBucket: 'fluttercompareapp.appspot.com',
    androidClientId: '685600365624-atollgbpl25br15pcouc9vv00222v89c.apps.googleusercontent.com',
    iosClientId: '685600365624-eup6gg58brt002qsglpcptsi6n2rsvuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttercompareapp',
  );
}
