name: fluttercompareapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

flutter_intl:
  main_locale: en
  enabled: true

dependencies:
  beamer: ^1.5.3
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^4.0.6
  drift_sqflite: ^2.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.4.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.5
  hooks_riverpod: ^2.1.3
  intl: ^0.17.0
  retrofit: ^3.3.1
  sentry_flutter: ^6.19.0
  loggy: ^2.0.3
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^2.0.1
  shake: ^2.2.0
  json_annotation: ^4.8.0
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_performance: ^0.9.1
  drift: ^2.6.0
  sqlite3_flutter_libs: ^0.5.13
  path_provider: ^2.0.14
  path: ^1.8.2

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.5.0
  flutter_flavorizr: ^2.1.5
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.6.0
  mocktail: ^0.3.0
  retrofit_generator: null
  state_notifier_test: ^0.0.9
  drift_dev: ^2.6.0

flutter:
  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300